autoreplies:
  repost: "Questo è un repost. Cerca prima di postare."
  "ask dmi": "Sarebbe opportuno rivolgere questa domanda in @Ask_DMI mediante il bot @Ask_DMI_Bot"
  rappresentanti: "Sarebbe opportuno rivolgere la domanda direttamente ai rappresentanti.\nPuoi consultarli direttamente o utilizzare il comando /report del @DMI_Bot"
  "gruppi materie": "Per avere informazioni riguardo la materia, consulta il gruppo Telegram apposito.\nPuoi trovare una lista completa su https://telegram.unictdev.org/. cliccando su 'DMI bachelor groups' o 'DMI Master's degree groups'."
  off-topic: "Questo è off-topic. Prova a postare qualcosa di più appropriato."
  cringe: "Hai postato cringe... Prova a postare qualcosa di più appropriato."
  "rispondi al post": "Rispondi al post, evita il flood."
  "no pirateria": "Non possiamo pubblicare il tuo post. Evitiamo la pirateria."
  offensivo: "Non possiamo pubblicare il tuo post sul canale perché il contenuto è offensivo, diffamatorio, violento o inappropriato."
  ersu: "contatta l'@ERSUbot ed utilizza il comando /report per contattare i rappresentanti dell'ERSU e di casa dello studente."
  "don't ask to ask": "Non chiedere se puoi fare una domanda, chiedi e basta.\nhttps://dontasktoask.com/it/"
