name: Lint

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"
      - "pyproject.toml"

  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "pyproject.toml"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[lint]

      - name: Lint with black
        run: black --check --diff src tests

      - name: Lint with pylint
        run: pylint src tests

      # Removed because coroutines :(
      # - name: Lint with mypy
      #   run: mypy src tests

      - name: Lint with isort
        run: isort --check-only --diff src tests
